<?php

use Illuminate\Database\Seeder;

class OrganizationsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('organizations')->insert([ 'id' => '1', 'code' => '1-brg', 'org_type' => '1', 'short_name' => 'BRG', 'full_name' => 'Badan Restorasi Gambut', ]);
        DB::table('organizations')->insert([ 'id' => '2', 'code' => '1-ksdae', 'org_type' => '1', 'short_name' => 'KSDAE', 'full_name' => 'Konservasi Sumber Daya Alam dan Ekosistem', ]);
        DB::table('organizations')->insert([ 'id' => '3', 'code' => '2-pemprov-riau', 'org_type' => '2', 'short_name' => 'Pemprov RIAU', 'full_name' => 'Pemerintah Provinsi Riau', 'work_scope' => 'provinsi', 'area_id' => '14', ]);
        DB::table('organizations')->insert([ 'id' => '4', 'code' => '2-pemprov-jambi', 'org_type' => '2', 'short_name' => 'Pemprov JAMBI', 'full_name' => 'Pemerintah Provinsi Jambi', 'work_scope' => 'provinsi', 'area_id' => '15', ]);
        DB::table('organizations')->insert([ 'id' => '5', 'code' => '2-pemprov-sumsel', 'org_type' => '2', 'short_name' => 'Pemprov SUMSEL', 'full_name' => 'Pemerintah Provinsi Sumatera Selatan', 'work_scope' => 'provinsi', 'area_id' => '21', ]);
        DB::table('organizations')->insert([ 'id' => '6', 'code' => '2-pemprov-kalbar', 'org_type' => '2', 'short_name' => 'Pemprov KALBAR', 'full_name' => 'Pemerintah Provinsi Kalimantan Barat', 'work_scope' => 'provinsi', 'area_id' => '41', ]);
        DB::table('organizations')->insert([ 'id' => '7', 'code' => '2-pemprov-kalteng', 'org_type' => '2', 'short_name' => 'Pemprov KALTENG', 'full_name' => 'Pemerintah Provinsi Kalimantan Tengah', 'work_scope' => 'provinsi', 'area_id' => '42', ]);
        DB::table('organizations')->insert([ 'id' => '8', 'code' => '2-pemprov-kalsel', 'org_type' => '2', 'short_name' => 'Pemprov KALSEL', 'full_name' => 'Pemerintah Provinsi Kalimantan Selatan', 'work_scope' => 'provinsi', 'area_id' => '43', ]);
        DB::table('organizations')->insert([ 'id' => '9', 'code' => '2-pemprov-papua', 'org_type' => '2', 'short_name' => 'Pemprov PAPUA', 'full_name' => 'Pemerintah Provinsi Papua', 'work_scope' => 'provinsi', 'area_id' => '73', ]);
        DB::table('organizations')->insert([ 'id' => '10', 'code' => '3-pemkab-kampar', 'org_type' => '3', 'short_name' => 'Pemkab Kampar', 'full_name' => 'Pemerintah Kabupaten Kampar', 'work_scope' => 'kota', 'area_id' => '1401', ]);
        DB::table('organizations')->insert([ 'id' => '11', 'code' => '3-pemkab-bengkalis', 'org_type' => '3', 'short_name' => 'Pemkab Bengkalis', 'full_name' => 'Pemerintah Kabupaten Bengkalis', 'work_scope' => 'kota', 'area_id' => '1402', ]);
        DB::table('organizations')->insert([ 'id' => '12', 'code' => '3-pemkab-indragiri-hulu', 'org_type' => '3', 'short_name' => 'Pemkab Indragiri Hulu', 'full_name' => 'Pemerintah Kabupaten Indragiri Hulu', 'work_scope' => 'kota', 'area_id' => '1403', ]);
        DB::table('organizations')->insert([ 'id' => '13', 'code' => '3-pemkab-indragiri-hilir', 'org_type' => '3', 'short_name' => 'Pemkab Indragiri Hilir', 'full_name' => 'Pemerintah Kabupaten Indragiri Hilir', 'work_scope' => 'kota', 'area_id' => '1404', ]);
        DB::table('organizations')->insert([ 'id' => '14', 'code' => '3-pemkab-pelalawan', 'org_type' => '3', 'short_name' => 'Pemkab Pelalawan', 'full_name' => 'Pemerintah Kabupaten Pelalawan', 'work_scope' => 'kota', 'area_id' => '1405', ]);
        DB::table('organizations')->insert([ 'id' => '15', 'code' => '3-pemkab-rokan-hulu', 'org_type' => '3', 'short_name' => 'Pemkab Rokan Hulu', 'full_name' => 'Pemerintah Kabupaten Rokan Hulu', 'work_scope' => 'kota', 'area_id' => '1406', ]);
        DB::table('organizations')->insert([ 'id' => '16', 'code' => '3-pemkab-rokan-hilir', 'org_type' => '3', 'short_name' => 'Pemkab Rokan Hilir', 'full_name' => 'Pemerintah Kabupaten Rokan Hilir', 'work_scope' => 'kota', 'area_id' => '1407', ]);
        DB::table('organizations')->insert([ 'id' => '17', 'code' => '3-pemkab-siak', 'org_type' => '3', 'short_name' => 'Pemkab Siak', 'full_name' => 'Pemerintah Kabupaten Siak', 'work_scope' => 'kota', 'area_id' => '1408', ]);
        DB::table('organizations')->insert([ 'id' => '18', 'code' => '3-pemkab-kuantan-singingi', 'org_type' => '3', 'short_name' => 'Pemkab Kuantan Singingi', 'full_name' => 'Pemerintah Kabupaten Kuantan Singingi', 'work_scope' => 'kota', 'area_id' => '1409', ]);
        DB::table('organizations')->insert([ 'id' => '19', 'code' => '3-pemkot-pekanbaru', 'org_type' => '3', 'short_name' => 'Pemkot Pekanbaru', 'full_name' => 'Pemerintah Kota Pekanbaru', 'work_scope' => 'kota', 'area_id' => '1410', ]);
        DB::table('organizations')->insert([ 'id' => '20', 'code' => '3-pemkot-dumai', 'org_type' => '3', 'short_name' => 'Pemkot Dumai', 'full_name' => 'Pemerintah Kota Dumai', 'work_scope' => 'kota', 'area_id' => '1411', ]);
        DB::table('organizations')->insert([ 'id' => '21', 'code' => '3-pemkab-kep-meranti', 'org_type' => '3', 'short_name' => 'Pemkab Kep. Meranti', 'full_name' => 'Pemerintah Kabupaten Kepulauan Meranti', 'work_scope' => 'kota', 'area_id' => '1412', ]);
        DB::table('organizations')->insert([ 'id' => '22', 'code' => '3-pemkab-batanghari', 'org_type' => '3', 'short_name' => 'Pemkab Batanghari', 'full_name' => 'Pemerintah Kabupaten Batanghari', 'work_scope' => 'kota', 'area_id' => '1501', ]);
        DB::table('organizations')->insert([ 'id' => '23', 'code' => '3-pemkab-bungo', 'org_type' => '3', 'short_name' => 'Pemkab Bungo', 'full_name' => 'Pemerintah Kabupaten Bungo', 'work_scope' => 'kota', 'area_id' => '1502', ]);
        DB::table('organizations')->insert([ 'id' => '24', 'code' => '3-pemkab-merangin', 'org_type' => '3', 'short_name' => 'Pemkab Merangin', 'full_name' => 'Pemerintah Kabupaten Merangin', 'work_scope' => 'kota', 'area_id' => '1503', ]);
        DB::table('organizations')->insert([ 'id' => '25', 'code' => '3-pemkab-tanjung-jabung-barat', 'org_type' => '3', 'short_name' => 'Pemkab Tanjung Jabung Barat', 'full_name' => 'Pemerintah Kabupaten Tanjung Jabung Barat', 'work_scope' => 'kota', 'area_id' => '1504', ]);
        DB::table('organizations')->insert([ 'id' => '26', 'code' => '3-pemkab-kerinci', 'org_type' => '3', 'short_name' => 'Pemkab Kerinci', 'full_name' => 'Pemerintah Kabupaten Kerinci', 'work_scope' => 'kota', 'area_id' => '1505', ]);
        DB::table('organizations')->insert([ 'id' => '27', 'code' => '3-pemkab-muaro-jambi', 'org_type' => '3', 'short_name' => 'Pemkab Muaro Jambi', 'full_name' => 'Pemerintah Kabupaten Muaro Jambi', 'work_scope' => 'kota', 'area_id' => '1506', ]);
        DB::table('organizations')->insert([ 'id' => '28', 'code' => '3-pemkab-tebo', 'org_type' => '3', 'short_name' => 'Pemkab Tebo', 'full_name' => 'Pemerintah Kabupaten Tebo', 'work_scope' => 'kota', 'area_id' => '1507', ]);
        DB::table('organizations')->insert([ 'id' => '29', 'code' => '3-pemkab-sarolangun', 'org_type' => '3', 'short_name' => 'Pemkab Sarolangun', 'full_name' => 'Pemerintah Kabupaten Sarolangun', 'work_scope' => 'kota', 'area_id' => '1508', ]);
        DB::table('organizations')->insert([ 'id' => '30', 'code' => '3-pemkab-tanjung-jabung-timur', 'org_type' => '3', 'short_name' => 'Pemkab Tanjung Jabung Timur', 'full_name' => 'Pemerintah Kabupaten Tanjung Jabung Timur', 'work_scope' => 'kota', 'area_id' => '1509', ]);
        DB::table('organizations')->insert([ 'id' => '31', 'code' => '3-pemkot-jambi', 'org_type' => '3', 'short_name' => 'Pemkot Jambi', 'full_name' => 'Pemerintah Kota Jambi', 'work_scope' => 'kota', 'area_id' => '1510', ]);
        DB::table('organizations')->insert([ 'id' => '32', 'code' => '3-pemkot-sungai-penuh', 'org_type' => '3', 'short_name' => 'Pemkot Sungai Penuh', 'full_name' => 'Pemerintah Kota Sungai Penuh', 'work_scope' => 'kota', 'area_id' => '1511', ]);
        DB::table('organizations')->insert([ 'id' => '33', 'code' => '3-pemkab-musi-banyuasin', 'org_type' => '3', 'short_name' => 'Pemkab Musi Banyuasin', 'full_name' => 'Pemerintah Kabupaten Musi Banyuasin', 'work_scope' => 'kota', 'area_id' => '2101', ]);
        DB::table('organizations')->insert([ 'id' => '34', 'code' => '3-pemkab-oki', 'org_type' => '3', 'short_name' => 'Pemkab OKI', 'full_name' => 'Pemerintah Kabupaten Ogan Komering Ilir', 'work_scope' => 'kota', 'area_id' => '2102', ]);
        DB::table('organizations')->insert([ 'id' => '35', 'code' => '3-pemkab-oku', 'org_type' => '3', 'short_name' => 'Pemkab OKU', 'full_name' => 'Pemerintah Kabupaten Ogan Komering Ulu', 'work_scope' => 'kota', 'area_id' => '2103', ]);
        DB::table('organizations')->insert([ 'id' => '36', 'code' => '3-pemkab-muara-enim', 'org_type' => '3', 'short_name' => 'Pemkab Muara Enim', 'full_name' => 'Pemerintah Kabupaten Muara Enim', 'work_scope' => 'kota', 'area_id' => '2104', ]);
        DB::table('organizations')->insert([ 'id' => '37', 'code' => '3-pemkab-lahat', 'org_type' => '3', 'short_name' => 'Pemkab Lahat', 'full_name' => 'Pemerintah Kabupaten Lahat', 'work_scope' => 'kota', 'area_id' => '2105', ]);
        DB::table('organizations')->insert([ 'id' => '38', 'code' => '3-pemkab-musi-rawas', 'org_type' => '3', 'short_name' => 'Pemkab Musi Rawas', 'full_name' => 'Pemerintah Kabupaten Musi Rawas', 'work_scope' => 'kota', 'area_id' => '2106', ]);
        DB::table('organizations')->insert([ 'id' => '39', 'code' => '3-pemkab-banyuasin', 'org_type' => '3', 'short_name' => 'Pemkab Banyuasin', 'full_name' => 'Pemerintah Kabupaten Banyuasin', 'work_scope' => 'kota', 'area_id' => '2107', ]);
        DB::table('organizations')->insert([ 'id' => '40', 'code' => '3-pemkab-ogan-ilir', 'org_type' => '3', 'short_name' => 'Pemkab Ogan Ilir', 'full_name' => 'Pemerintah Kabupaten Ogan Ilir', 'work_scope' => 'kota', 'area_id' => '2108', ]);
        DB::table('organizations')->insert([ 'id' => '41', 'code' => '3-pemkab-oku-selatan', 'org_type' => '3', 'short_name' => 'Pemkab OKU Selatan', 'full_name' => 'Pemerintah Kabupaten Ogan Komering Ulu Selatan', 'work_scope' => 'kota', 'area_id' => '2109', ]);
        DB::table('organizations')->insert([ 'id' => '42', 'code' => '3-pemkab-oku-timur', 'org_type' => '3', 'short_name' => 'Pemkab OKU Timur', 'full_name' => 'Pemerintah Kabupaten Ogan Komering Ulu Timur', 'work_scope' => 'kota', 'area_id' => '2110', ]);
        DB::table('organizations')->insert([ 'id' => '43', 'code' => '3-pemkot-palembang', 'org_type' => '3', 'short_name' => 'Pemkot Palembang', 'full_name' => 'Pemerintah Kota Palembang', 'work_scope' => 'kota', 'area_id' => '2111', ]);
        DB::table('organizations')->insert([ 'id' => '44', 'code' => '3-pemkot-lubuk-linggau', 'org_type' => '3', 'short_name' => 'Pemkot Lubuk Linggau', 'full_name' => 'Pemerintah Kota Lubuk Linggau', 'work_scope' => 'kota', 'area_id' => '2112', ]);
        DB::table('organizations')->insert([ 'id' => '45', 'code' => '3-pemkot-prabumulih', 'org_type' => '3', 'short_name' => 'Pemkot Prabumulih', 'full_name' => 'Pemerintah Kota Prabumulih', 'work_scope' => 'kota', 'area_id' => '2113', ]);
        DB::table('organizations')->insert([ 'id' => '46', 'code' => '3-pemkot-pagar-alam', 'org_type' => '3', 'short_name' => 'Pemkot Pagar Alam', 'full_name' => 'Pemerintah Kota Pagar Alam', 'work_scope' => 'kota', 'area_id' => '2114', ]);
        DB::table('organizations')->insert([ 'id' => '47', 'code' => '3-pemkab-empat-lawang', 'org_type' => '3', 'short_name' => 'Pemkab Empat Lawang', 'full_name' => 'Pemerintah Kabupaten Empat Lawang', 'work_scope' => 'kota', 'area_id' => '2115', ]);
        DB::table('organizations')->insert([ 'id' => '48', 'code' => '3-pemkab-pali', 'org_type' => '3', 'short_name' => 'Pemkab PALI', 'full_name' => 'Pemerintah Kabupaten Penukal Abab Lematang Ilir', 'work_scope' => 'kota', 'area_id' => '2116', ]);
        DB::table('organizations')->insert([ 'id' => '49', 'code' => '3-pemkab-musi-rawas-utara', 'org_type' => '3', 'short_name' => 'Pemkab Musi Rawas Utara', 'full_name' => 'Pemerintah Kabupaten Musi Rawas Utara', 'work_scope' => 'kota', 'area_id' => '2117', ]);
        DB::table('organizations')->insert([ 'id' => '50', 'code' => '3-pemkab-sambas', 'org_type' => '3', 'short_name' => 'Pemkab Sambas', 'full_name' => 'Pemerintah Kabupaten Sambas', 'work_scope' => 'kota', 'area_id' => '4101', ]);
        DB::table('organizations')->insert([ 'id' => '51', 'code' => '3-pemkab-mempawah', 'org_type' => '3', 'short_name' => 'Pemkab Mempawah', 'full_name' => 'Pemerintah Kabupaten Mempawah', 'work_scope' => 'kota', 'area_id' => '4102', ]);
        DB::table('organizations')->insert([ 'id' => '52', 'code' => '3-pemkab-sanggau', 'org_type' => '3', 'short_name' => 'Pemkab Sanggau', 'full_name' => 'Pemerintah Kabupaten Sanggau', 'work_scope' => 'kota', 'area_id' => '4103', ]);
        DB::table('organizations')->insert([ 'id' => '53', 'code' => '3-pemkab-sintang', 'org_type' => '3', 'short_name' => 'Pemkab Sintang', 'full_name' => 'Pemerintah Kabupaten Sintang', 'work_scope' => 'kota', 'area_id' => '4104', ]);
        DB::table('organizations')->insert([ 'id' => '54', 'code' => '3-pemkab-kapuas-hulu', 'org_type' => '3', 'short_name' => 'Pemkab Kapuas Hulu', 'full_name' => 'Pemerintah Kabupaten Kapuas Hulu', 'work_scope' => 'kota', 'area_id' => '4105', ]);
        DB::table('organizations')->insert([ 'id' => '55', 'code' => '3-pemkab-ketapang', 'org_type' => '3', 'short_name' => 'Pemkab Ketapang', 'full_name' => 'Pemerintah Kabupaten Ketapang', 'work_scope' => 'kota', 'area_id' => '4106', ]);
        DB::table('organizations')->insert([ 'id' => '56', 'code' => '3-pemkab-bengkayang', 'org_type' => '3', 'short_name' => 'Pemkab Bengkayang', 'full_name' => 'Pemerintah Kabupaten Bengkayang', 'work_scope' => 'kota', 'area_id' => '4107', ]);
        DB::table('organizations')->insert([ 'id' => '57', 'code' => '3-pemkab-landak', 'org_type' => '3', 'short_name' => 'Pemkab Landak', 'full_name' => 'Pemerintah Kabupaten Landak', 'work_scope' => 'kota', 'area_id' => '4108', ]);
        DB::table('organizations')->insert([ 'id' => '58', 'code' => '3-pemkab-melawi', 'org_type' => '3', 'short_name' => 'Pemkab Melawi', 'full_name' => 'Pemerintah Kabupaten Melawi', 'work_scope' => 'kota', 'area_id' => '4109', ]);
        DB::table('organizations')->insert([ 'id' => '59', 'code' => '3-pemkot-pontianak', 'org_type' => '3', 'short_name' => 'Pemkot Pontianak', 'full_name' => 'Pemerintah Kota Pontianak', 'work_scope' => 'kota', 'area_id' => '4110', ]);
        DB::table('organizations')->insert([ 'id' => '60', 'code' => '3-pemkot-singkawang', 'org_type' => '3', 'short_name' => 'Pemkot Singkawang', 'full_name' => 'Pemerintah Kota Singkawang', 'work_scope' => 'kota', 'area_id' => '4111', ]);
        DB::table('organizations')->insert([ 'id' => '61', 'code' => '3-pemkab-sekadau', 'org_type' => '3', 'short_name' => 'Pemkab Sekadau', 'full_name' => 'Pemerintah Kabupaten Sekadau', 'work_scope' => 'kota', 'area_id' => '4112', ]);
        DB::table('organizations')->insert([ 'id' => '62', 'code' => '3-pemkab-kayong-utara', 'org_type' => '3', 'short_name' => 'Pemkab Kayong Utara', 'full_name' => 'Pemerintah Kabupaten Kayong Utara', 'work_scope' => 'kota', 'area_id' => '4113', ]);
        DB::table('organizations')->insert([ 'id' => '63', 'code' => '3-pemkab-kubu-raya', 'org_type' => '3', 'short_name' => 'Pemkab Kubu Raya', 'full_name' => 'Pemerintah Kabupaten Kubu Raya', 'work_scope' => 'kota', 'area_id' => '4114', ]);
        DB::table('organizations')->insert([ 'id' => '64', 'code' => '3-pemkab-kapuas', 'org_type' => '3', 'short_name' => 'Pemkab Kapuas', 'full_name' => 'Pemerintah Kabupaten Kapuas', 'work_scope' => 'kota', 'area_id' => '4201', ]);
        DB::table('organizations')->insert([ 'id' => '65', 'code' => '3-pemkab-barito-selatan', 'org_type' => '3', 'short_name' => 'Pemkab Barito Selatan', 'full_name' => 'Pemerintah Kabupaten Barito Selatan', 'work_scope' => 'kota', 'area_id' => '4202', ]);
        DB::table('organizations')->insert([ 'id' => '66', 'code' => '3-pemkab-barito-utara', 'org_type' => '3', 'short_name' => 'Pemkab Barito Utara', 'full_name' => 'Pemerintah Kabupaten Barito Utara', 'work_scope' => 'kota', 'area_id' => '4203', ]);
        DB::table('organizations')->insert([ 'id' => '67', 'code' => '3-pemkab-kotawaringin-timur', 'org_type' => '3', 'short_name' => 'Pemkab Kotawaringin Timur', 'full_name' => 'Pemerintah Kabupaten Kotawaringin Timur', 'work_scope' => 'kota', 'area_id' => '4204', ]);
        DB::table('organizations')->insert([ 'id' => '68', 'code' => '3-pemkab-kotawaringin-barat', 'org_type' => '3', 'short_name' => 'Pemkab Kotawaringin Barat', 'full_name' => 'Pemerintah Kabupaten Kotawaringin Barat', 'work_scope' => 'kota', 'area_id' => '4205', ]);
        DB::table('organizations')->insert([ 'id' => '69', 'code' => '3-pemkab-pulang-pisau', 'org_type' => '3', 'short_name' => 'Pemkab Pulang Pisau', 'full_name' => 'Pemerintah Kabupaten Pulang Pisau', 'work_scope' => 'kota', 'area_id' => '4206', ]);
        DB::table('organizations')->insert([ 'id' => '70', 'code' => '3-pemkab-gunung-mas', 'org_type' => '3', 'short_name' => 'Pemkab Gunung Mas', 'full_name' => 'Pemerintah Kabupaten Gunung Mas', 'work_scope' => 'kota', 'area_id' => '4207', ]);
        DB::table('organizations')->insert([ 'id' => '71', 'code' => '3-pemkab-barito-timur', 'org_type' => '3', 'short_name' => 'Pemkab Barito Timur', 'full_name' => 'Pemerintah Kabupaten Barito Timur', 'work_scope' => 'kota', 'area_id' => '4208', ]);
        DB::table('organizations')->insert([ 'id' => '72', 'code' => '3-pemkab-sukamara', 'org_type' => '3', 'short_name' => 'Pemkab Sukamara', 'full_name' => 'Pemerintah Kabupaten Sukamara', 'work_scope' => 'kota', 'area_id' => '4209', ]);
        DB::table('organizations')->insert([ 'id' => '73', 'code' => '3-pemkab-katingan', 'org_type' => '3', 'short_name' => 'Pemkab Katingan', 'full_name' => 'Pemerintah Kabupaten Katingan', 'work_scope' => 'kota', 'area_id' => '4210', ]);
        DB::table('organizations')->insert([ 'id' => '74', 'code' => '3-pemkab-lamandau', 'org_type' => '3', 'short_name' => 'Pemkab Lamandau', 'full_name' => 'Pemerintah Kabupaten Lamandau', 'work_scope' => 'kota', 'area_id' => '4211', ]);
        DB::table('organizations')->insert([ 'id' => '75', 'code' => '3-pemkab-seruyan', 'org_type' => '3', 'short_name' => 'Pemkab Seruyan', 'full_name' => 'Pemerintah Kabupaten Seruyan', 'work_scope' => 'kota', 'area_id' => '4212', ]);
        DB::table('organizations')->insert([ 'id' => '76', 'code' => '3-pemkab-murung-raya', 'org_type' => '3', 'short_name' => 'Pemkab Murung Raya', 'full_name' => 'Pemerintah Kabupaten Murung Raya', 'work_scope' => 'kota', 'area_id' => '4213', ]);
        DB::table('organizations')->insert([ 'id' => '77', 'code' => '3-pemkot-palangkaraya', 'org_type' => '3', 'short_name' => 'Pemkot Palangkaraya', 'full_name' => 'Pemerintah Kota Palangkaraya', 'work_scope' => 'kota', 'area_id' => '4214', ]);
        DB::table('organizations')->insert([ 'id' => '78', 'code' => '3-pemkab-banjar', 'org_type' => '3', 'short_name' => 'Pemkab Banjar', 'full_name' => 'Pemerintah Kabupaten Banjar', 'work_scope' => 'kota', 'area_id' => '4301', ]);
        DB::table('organizations')->insert([ 'id' => '79', 'code' => '3-pemkab-tanah-laut', 'org_type' => '3', 'short_name' => 'Pemkab Tanah Laut', 'full_name' => 'Pemerintah Kabupaten Tanah Laut', 'work_scope' => 'kota', 'area_id' => '4302', ]);
        DB::table('organizations')->insert([ 'id' => '80', 'code' => '3-pemkab-barito-kuala', 'org_type' => '3', 'short_name' => 'Pemkab Barito Kuala', 'full_name' => 'Pemerintah Kabupaten Barito Kuala', 'work_scope' => 'kota', 'area_id' => '4303', ]);
        DB::table('organizations')->insert([ 'id' => '81', 'code' => '3-pemkab-tapin', 'org_type' => '3', 'short_name' => 'Pemkab Tapin', 'full_name' => 'Pemerintah Kabupaten Tapin', 'work_scope' => 'kota', 'area_id' => '4304', ]);
        DB::table('organizations')->insert([ 'id' => '82', 'code' => '3-pemkab-hulu-sungai-selatan', 'org_type' => '3', 'short_name' => 'Pemkab Hulu Sungai Selatan', 'full_name' => 'Pemerintah Kabupaten Hulu Sungai Selatan', 'work_scope' => 'kota', 'area_id' => '4305', ]);
        DB::table('organizations')->insert([ 'id' => '83', 'code' => '3-pemkab-hulu-sungai-tengah', 'org_type' => '3', 'short_name' => 'Pemkab Hulu Sungai Tengah', 'full_name' => 'Pemerintah Kabupaten Hulu Sungai Tengah', 'work_scope' => 'kota', 'area_id' => '4306', ]);
        DB::table('organizations')->insert([ 'id' => '84', 'code' => '3-pemkab-hulu-sungai-utara', 'org_type' => '3', 'short_name' => 'Pemkab Hulu Sungai Utara', 'full_name' => 'Pemerintah Kabupaten Hulu Sungai Utara', 'work_scope' => 'kota', 'area_id' => '4307', ]);
        DB::table('organizations')->insert([ 'id' => '85', 'code' => '3-pemkab-tabalong', 'org_type' => '3', 'short_name' => 'Pemkab Tabalong', 'full_name' => 'Pemerintah Kabupaten Tabalong', 'work_scope' => 'kota', 'area_id' => '4308', ]);
        DB::table('organizations')->insert([ 'id' => '86', 'code' => '3-pemkab-kotabaru', 'org_type' => '3', 'short_name' => 'Pemkab Kotabaru', 'full_name' => 'Pemerintah Kabupaten Kotabaru', 'work_scope' => 'kota', 'area_id' => '4309', ]);
        DB::table('organizations')->insert([ 'id' => '87', 'code' => '3-pemkab-tanah-bumbu', 'org_type' => '3', 'short_name' => 'Pemkab Tanah Bumbu', 'full_name' => 'Pemerintah Kabupaten Tanah Bumbu', 'work_scope' => 'kota', 'area_id' => '4310', ]);
        DB::table('organizations')->insert([ 'id' => '88', 'code' => '3-pemkab-balangan', 'org_type' => '3', 'short_name' => 'Pemkab Balangan', 'full_name' => 'Pemerintah Kabupaten Balangan', 'work_scope' => 'kota', 'area_id' => '4311', ]);
        DB::table('organizations')->insert([ 'id' => '89', 'code' => '3-pemkot-banjarmasin', 'org_type' => '3', 'short_name' => 'Pemkot Banjarmasin', 'full_name' => 'Pemerintah Kota Banjarmasin', 'work_scope' => 'kota', 'area_id' => '4312', ]);
        DB::table('organizations')->insert([ 'id' => '90', 'code' => '3-pemkot-banjarbaru', 'org_type' => '3', 'short_name' => 'Pemkot Banjarbaru', 'full_name' => 'Pemerintah Kota Banjarbaru', 'work_scope' => 'kota', 'area_id' => '4313', ]);
        DB::table('organizations')->insert([ 'id' => '91', 'code' => '3-pemkab-jayapura', 'org_type' => '3', 'short_name' => 'Pemkab Jayapura', 'full_name' => 'Pemerintah Kabupaten Jayapura', 'work_scope' => 'kota', 'area_id' => '7301', ]);
        DB::table('organizations')->insert([ 'id' => '92', 'code' => '3-pemkab-biak-numfor', 'org_type' => '3', 'short_name' => 'Pemkab Biak Numfor', 'full_name' => 'Pemerintah Kabupaten Biak Numfor', 'work_scope' => 'kota', 'area_id' => '7302', ]);
        DB::table('organizations')->insert([ 'id' => '93', 'code' => '3-pemkab-kep-yapen', 'org_type' => '3', 'short_name' => 'Pemkab Kep. Yapen', 'full_name' => 'Pemerintah Kabupaten Kepulauan Yapen', 'work_scope' => 'kota', 'area_id' => '7303', ]);
        DB::table('organizations')->insert([ 'id' => '94', 'code' => '3-pemkab-merauke', 'org_type' => '3', 'short_name' => 'Pemkab Merauke', 'full_name' => 'Pemerintah Kabupaten Merauke', 'work_scope' => 'kota', 'area_id' => '7304', ]);
        DB::table('organizations')->insert([ 'id' => '95', 'code' => '3-pemkab-jayawijaya', 'org_type' => '3', 'short_name' => 'Pemkab Jayawijaya', 'full_name' => 'Pemerintah Kabupaten Jayawijaya', 'work_scope' => 'kota', 'area_id' => '7305', ]);
        DB::table('organizations')->insert([ 'id' => '96', 'code' => '3-pemkab-paniai', 'org_type' => '3', 'short_name' => 'Pemkab Paniai', 'full_name' => 'Pemerintah Kabupaten Paniai', 'work_scope' => 'kota', 'area_id' => '7306', ]);
        DB::table('organizations')->insert([ 'id' => '97', 'code' => '3-pemkab-nabire', 'org_type' => '3', 'short_name' => 'Pemkab Nabire', 'full_name' => 'Pemerintah Kabupaten Nabire', 'work_scope' => 'kota', 'area_id' => '7307', ]);
        DB::table('organizations')->insert([ 'id' => '98', 'code' => '3-pemkab-puncak-jaya', 'org_type' => '3', 'short_name' => 'Pemkab Puncak Jaya', 'full_name' => 'Pemerintah Kabupaten Puncak Jaya', 'work_scope' => 'kota', 'area_id' => '7308', ]);
        DB::table('organizations')->insert([ 'id' => '99', 'code' => '3-pemkab-mimika', 'org_type' => '3', 'short_name' => 'Pemkab Mimika', 'full_name' => 'Pemerintah Kabupaten Mimika', 'work_scope' => 'kota', 'area_id' => '7309', ]);
        DB::table('organizations')->insert([ 'id' => '100', 'code' => '3-pemkab-keerom', 'org_type' => '3', 'short_name' => 'Pemkab Keerom', 'full_name' => 'Pemerintah Kabupaten Keerom', 'work_scope' => 'kota', 'area_id' => '7310', ]);
        DB::table('organizations')->insert([ 'id' => '101', 'code' => '3-pemkab-sarmi', 'org_type' => '3', 'short_name' => 'Pemkab Sarmi', 'full_name' => 'Pemerintah Kabupaten Sarmi', 'work_scope' => 'kota', 'area_id' => '7311', ]);
        DB::table('organizations')->insert([ 'id' => '102', 'code' => '3-pemkab-asmat', 'org_type' => '3', 'short_name' => 'Pemkab Asmat', 'full_name' => 'Pemerintah Kabupaten Asmat', 'work_scope' => 'kota', 'area_id' => '7312', ]);
        DB::table('organizations')->insert([ 'id' => '103', 'code' => '3-pemkab-mappi', 'org_type' => '3', 'short_name' => 'Pemkab Mappi', 'full_name' => 'Pemerintah Kabupaten Mappi', 'work_scope' => 'kota', 'area_id' => '7313', ]);
        DB::table('organizations')->insert([ 'id' => '104', 'code' => '3-pemkab-boven-digul', 'org_type' => '3', 'short_name' => 'Pemkab Boven Digul', 'full_name' => 'Pemerintah Kabupaten Boven Digul', 'work_scope' => 'kota', 'area_id' => '7314', ]);
        DB::table('organizations')->insert([ 'id' => '105', 'code' => '3-pemkab-yahukimo', 'org_type' => '3', 'short_name' => 'Pemkab Yahukimo', 'full_name' => 'Pemerintah Kabupaten Yahukimo', 'work_scope' => 'kota', 'area_id' => '7315', ]);
        DB::table('organizations')->insert([ 'id' => '106', 'code' => '3-pemkab-pegunungan-bintang', 'org_type' => '3', 'short_name' => 'Pemkab Pegunungan Bintang', 'full_name' => 'Pemerintah Kabupaten Pegunungan Bintang', 'work_scope' => 'kota', 'area_id' => '7316', ]);
        DB::table('organizations')->insert([ 'id' => '107', 'code' => '3-pemkab-supiori', 'org_type' => '3', 'short_name' => 'Pemkab Supiori', 'full_name' => 'Pemerintah Kabupaten Supiori', 'work_scope' => 'kota', 'area_id' => '7317', ]);
        DB::table('organizations')->insert([ 'id' => '108', 'code' => '3-pemkab-waropen', 'org_type' => '3', 'short_name' => 'Pemkab Waropen', 'full_name' => 'Pemerintah Kabupaten Waropen', 'work_scope' => 'kota', 'area_id' => '7318', ]);
        DB::table('organizations')->insert([ 'id' => '109', 'code' => '3-pemkab-tolikara', 'org_type' => '3', 'short_name' => 'Pemkab Tolikara', 'full_name' => 'Pemerintah Kabupaten Tolikara', 'work_scope' => 'kota', 'area_id' => '7319', ]);
        DB::table('organizations')->insert([ 'id' => '110', 'code' => '3-pemkot-jayapura', 'org_type' => '3', 'short_name' => 'Pemkot Jayapura', 'full_name' => 'Pemerintah Kota Jayapura', 'work_scope' => 'kota', 'area_id' => '7320', ]);
        DB::table('organizations')->insert([ 'id' => '111', 'code' => '3-pemkab-mamberamo-raya', 'org_type' => '3', 'short_name' => 'Pemkab Mamberamo Raya', 'full_name' => 'Pemerintah Kabupaten Mamberamo Raya', 'work_scope' => 'kota', 'area_id' => '7321', ]);
        DB::table('organizations')->insert([ 'id' => '112', 'code' => '3-pemkab-dogiyai', 'org_type' => '3', 'short_name' => 'Pemkab Dogiyai', 'full_name' => 'Pemerintah Kabupaten Dogiyai', 'work_scope' => 'kota', 'area_id' => '7322', ]);
        DB::table('organizations')->insert([ 'id' => '113', 'code' => '3-pemkab-lanny-jaya', 'org_type' => '3', 'short_name' => 'Pemkab Lanny Jaya', 'full_name' => 'Pemerintah Kabupaten Lanny Jaya', 'work_scope' => 'kota', 'area_id' => '7323', ]);
        DB::table('organizations')->insert([ 'id' => '114', 'code' => '3-pemkab-mamberamo-tengah', 'org_type' => '3', 'short_name' => 'Pemkab Mamberamo Tengah', 'full_name' => 'Pemerintah Kabupaten Mamberamo Tengah', 'work_scope' => 'kota', 'area_id' => '7324', ]);
        DB::table('organizations')->insert([ 'id' => '115', 'code' => '3-pemkab-nduga', 'org_type' => '3', 'short_name' => 'Pemkab Nduga', 'full_name' => 'Pemerintah Kabupaten Nduga', 'work_scope' => 'kota', 'area_id' => '7325', ]);
        DB::table('organizations')->insert([ 'id' => '116', 'code' => '3-pemkab-puncak', 'org_type' => '3', 'short_name' => 'Pemkab Puncak', 'full_name' => 'Pemerintah Kabupaten Puncak', 'work_scope' => 'kota', 'area_id' => '7326', ]);
        DB::table('organizations')->insert([ 'id' => '117', 'code' => '3-pemkab-yalimo', 'org_type' => '3', 'short_name' => 'Pemkab Yalimo', 'full_name' => 'Pemerintah Kabupaten Yalimo', 'work_scope' => 'kota', 'area_id' => '7327', ]);
        DB::table('organizations')->insert([ 'id' => '118', 'code' => '3-pemkab-intan-jaya', 'org_type' => '3', 'short_name' => 'Pemkab Intan Jaya', 'full_name' => 'Pemerintah Kabupaten Intan Jaya', 'work_scope' => 'kota', 'area_id' => '7328', ]);
        DB::table('organizations')->insert([ 'id' => '119', 'code' => '3-pemkab-deiyai', 'org_type' => '3', 'short_name' => 'Pemkab Deiyai', 'full_name' => 'Pemerintah Kabupaten Deiyai', 'work_scope' => 'kota', 'area_id' => '7329', ]);
    }
}
