<?php

use Illuminate\Database\Seeder;

class RetentionBasinPlansTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('retention_basin_plans')->insert([ 'id' => '1', 'code' => '2018_R1.4_15_00001', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1506', 'sub_district_id' => '1506003', 'village' => 'GEDONG KARYA', 'year' => '2018', 'remark' => 'Semak/Belukar', 'uprg_slug' => '1-tahura', 'uprg_text' => 'PEMERINTAH DAERAH JAMBI (TAHURA ORANG KAYO HITAM)', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '2', 'code' => '2018_R1.4_15_00002', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1506', 'sub_district_id' => '1506003', 'village' => 'JEBUS', 'year' => '2018', 'remark' => 'Semak/Belukar', 'uprg_slug' => '1-tahura', 'uprg_text' => 'PEMERINTAH DAERAH JAMBI (TAHURA ORANG KAYO HITAM)', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '3', 'code' => '2018_R1.4_15_00003', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1506', 'sub_district_id' => '1506003', 'village' => 'SUNGAI AUR', 'year' => '2018', 'remark' => 'Semak/Belukar', 'uprg_slug' => '1-tahura', 'uprg_text' => 'PEMERINTAH DAERAH JAMBI (TAHURA ORANG KAYO HITAM)', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '4', 'code' => '2018_R1.4_15_00004', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '5', 'code' => '2018_R1.4_15_00005', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '0', 'village' => 'HUTAN', 'year' => '2018', 'remark' => 'Tanah Terbuka', 'uprg_slug' => '1-tahura', 'uprg_text' => 'PEMERINTAH DAERAH JAMBI (TAHURA ORANG KAYO HITAM)', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '6', 'code' => '2018_R1.4_15_00006', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1506', 'sub_district_id' => '1506003', 'village' => 'SUNGAI AUR', 'year' => '2018', 'remark' => 'Tanah Terbuka', 'uprg_slug' => '1-tahura', 'uprg_text' => 'PEMERINTAH DAERAH JAMBI (TAHURA ORANG KAYO HITAM)', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '7', 'code' => '2018_R1.4_15_00007', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '0', 'village' => 'HUTAN', 'year' => '2018', 'remark' => 'Tanah Terbuka', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '8', 'code' => '2018_R1.4_15_00008', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503019', 'village' => 'REMAU BAKU TUO', 'year' => '2018', 'remark' => 'Tanah Terbuka', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '9', 'code' => '2018_R1.4_15_00009', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503019', 'village' => 'REMAU BAKU TUO', 'year' => '2018', 'remark' => 'Tanah Terbuka', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '10', 'code' => '2018_R1.4_15_00010', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '0', 'village' => 'HUTAN', 'year' => '2018', 'remark' => 'Tanah Terbuka', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '11', 'code' => '2018_R1.4_15_00011', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '0', 'village' => 'HUTAN', 'year' => '2018', 'remark' => 'Tanah Terbuka', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '12', 'code' => '2018_R1.4_15_00012', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1506', 'sub_district_id' => '1506003', 'village' => 'SUNGAI AUR', 'year' => '2018', 'remark' => 'Tanah Terbuka', 'uprg_slug' => '1-tahura', 'uprg_text' => 'PEMERINTAH DAERAH JAMBI (TAHURA ORANG KAYO HITAM)', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '13', 'code' => '2018_R1.4_15_00013', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '0', 'village' => 'HUTAN', 'year' => '2018', 'remark' => 'Belukar Rawa', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '14', 'code' => '2018_R1.4_15_00014', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '0', 'village' => 'HUTAN', 'year' => '2018', 'remark' => 'Belukar Rawa', 'uprg_slug' => '1-tahura', 'uprg_text' => 'PEMERINTAH DAERAH JAMBI (TAHURA ORANG KAYO HITAM)', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '15', 'code' => '2018_R1.4_15_00015', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '0', 'village' => 'HUTAN', 'year' => '2018', 'remark' => 'Belukar Rawa', 'uprg_slug' => '1-tahura', 'uprg_text' => 'PEMERINTAH DAERAH JAMBI (TAHURA ORANG KAYO HITAM)', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '16', 'code' => '2018_R1.4_15_00016', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1506', 'sub_district_id' => '1506003', 'village' => 'SUNGAI AUR', 'year' => '2018', 'remark' => 'Semak/Belukar', 'uprg_slug' => '1-tahura', 'uprg_text' => 'PEMERINTAH DAERAH JAMBI (TAHURA ORANG KAYO HITAM)', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '17', 'code' => '2018_R1.4_15_00017', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1506', 'sub_district_id' => '1506003', 'village' => 'SUNGAI AUR', 'year' => '2018', 'remark' => 'Semak/Belukar', 'uprg_slug' => '1-tahura', 'uprg_text' => 'PEMERINTAH DAERAH JAMBI (TAHURA ORANG KAYO HITAM)', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '18', 'code' => '2018_R1.4_15_00018', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1506', 'sub_district_id' => '1506003', 'village' => 'SUNGAI AUR', 'year' => '2018', 'remark' => 'Semak/Belukar', 'uprg_slug' => '1-tahura', 'uprg_text' => 'PEMERINTAH DAERAH JAMBI (TAHURA ORANG KAYO HITAM)', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '19', 'code' => '2018_R1.4_15_00019', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1506', 'sub_district_id' => '1506003', 'village' => 'SUNGAI AUR', 'year' => '2018', 'remark' => 'Semak/Belukar', 'uprg_slug' => '1-tahura', 'uprg_text' => 'PEMERINTAH DAERAH JAMBI (TAHURA ORANG KAYO HITAM)', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '20', 'code' => '2018_R1.4_15_00020', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1506', 'sub_district_id' => '1506003', 'village' => 'SUNGAI AUR', 'year' => '2018', 'remark' => 'Semak/Belukar', 'uprg_slug' => '1-tahura', 'uprg_text' => 'PEMERINTAH DAERAH JAMBI (TAHURA ORANG KAYO HITAM)', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '21', 'code' => '2018_R1.4_15_00021', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1506', 'sub_district_id' => '1506003', 'village' => 'SUNGAI AUR', 'year' => '2018', 'remark' => 'Semak/Belukar', 'uprg_slug' => '1-tahura', 'uprg_text' => 'PEMERINTAH DAERAH JAMBI (TAHURA ORANG KAYO HITAM)', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '22', 'code' => '2018_R1.4_15_00022', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1506', 'sub_district_id' => '1506003', 'village' => 'SUNGAI AUR', 'year' => '2018', 'remark' => 'Semak/Belukar', 'uprg_slug' => '1-tahura', 'uprg_text' => 'PEMERINTAH DAERAH JAMBI (TAHURA ORANG KAYO HITAM)', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '23', 'code' => '2018_R1.4_15_00023', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1506', 'sub_district_id' => '1506003', 'village' => 'SUNGAI AUR', 'year' => '2018', 'remark' => 'Semak/Belukar', 'uprg_slug' => '1-tahura', 'uprg_text' => 'PEMERINTAH DAERAH JAMBI (TAHURA ORANG KAYO HITAM)', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '24', 'code' => '2018_R1.4_15_00024', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1506', 'sub_district_id' => '1506003', 'village' => 'SUNGAI AUR', 'year' => '2018', 'remark' => 'Semak/Belukar', 'uprg_slug' => '1-tahura', 'uprg_text' => 'PEMERINTAH DAERAH JAMBI (TAHURA ORANG KAYO HITAM)', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '25', 'code' => '2018_R1.4_15_00025', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1506', 'sub_district_id' => '1506003', 'village' => 'SUNGAI AUR', 'year' => '2018', 'remark' => 'Semak/Belukar', 'uprg_slug' => '1-tahura', 'uprg_text' => 'PEMERINTAH DAERAH JAMBI (TAHURA ORANG KAYO HITAM)', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '26', 'code' => '2018_R1.4_15_00026', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1506', 'sub_district_id' => '1506003', 'village' => 'SUNGAI AUR', 'year' => '2018', 'remark' => 'Semak/Belukar', 'uprg_slug' => '1-tahura', 'uprg_text' => 'PEMERINTAH DAERAH JAMBI (TAHURA ORANG KAYO HITAM)', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '27', 'code' => '2018_R1.4_15_00027', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '28', 'code' => '2018_R1.4_15_00028', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '29', 'code' => '2018_R1.4_15_00029', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '30', 'code' => '2018_R1.4_15_00030', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '31', 'code' => '2018_R1.4_15_00031', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '32', 'code' => '2018_R1.4_15_00032', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '33', 'code' => '2018_R1.4_15_00033', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '34', 'code' => '2018_R1.4_15_00034', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '35', 'code' => '2018_R1.4_15_00035', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '36', 'code' => '2018_R1.4_15_00036', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '37', 'code' => '2018_R1.4_15_00037', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '38', 'code' => '2018_R1.4_15_00038', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '39', 'code' => '2018_R1.4_15_00039', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '40', 'code' => '2018_R1.4_15_00040', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '41', 'code' => '2018_R1.4_15_00041', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '42', 'code' => '2018_R1.4_15_00042', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '43', 'code' => '2018_R1.4_15_00043', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '44', 'code' => '2018_R1.4_15_00044', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '45', 'code' => '2018_R1.4_15_00045', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '46', 'code' => '2018_R1.4_15_00046', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '47', 'code' => '2018_R1.4_15_00047', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '48', 'code' => '2018_R1.4_15_00048', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '49', 'code' => '2018_R1.4_15_00049', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '50', 'code' => '2018_R1.4_15_00050', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '51', 'code' => '2018_R1.4_15_00051', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '52', 'code' => '2018_R1.4_15_00052', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '53', 'code' => '2018_R1.4_15_00053', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '54', 'code' => '2018_R1.4_15_00054', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '55', 'code' => '2018_R1.4_15_00055', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '56', 'code' => '2018_R1.4_15_00056', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '57', 'code' => '2018_R1.4_15_00057', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '58', 'code' => '2018_R1.4_15_00058', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503008', 'village' => 'RANTAU RASAU DESA', 'year' => '2018', 'remark' => 'Perkebunan', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '59', 'code' => '2018_R1.4_15_00059', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '0', 'village' => 'HUTAN', 'year' => '2018', 'remark' => 'Tanah Terbuka', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '60', 'code' => '2018_R1.4_15_00060', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '0', 'village' => 'HUTAN', 'year' => '2018', 'remark' => 'Tanah Terbuka', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '61', 'code' => '2018_R1.4_15_00061', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503019', 'village' => 'REMAU BAKU TUO', 'year' => '2018', 'remark' => 'Tanah Terbuka', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '62', 'code' => '2018_R1.4_15_00062', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503019', 'village' => 'REMAU BAKU TUO', 'year' => '2018', 'remark' => 'Tanah Terbuka', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
        DB::table('retention_basin_plans')->insert([ 'id' => '63', 'code' => '2018_R1.4_15_00063', 'phu_id' => '63', 'province_id' => '15', 'city_id' => '1509', 'sub_district_id' => '1503019', 'village' => 'REMAU BAKU TUO', 'year' => '2018', 'remark' => 'Tanah Terbuka', 'uprg_slug' => '1-tn-berbak', 'uprg_text' => 'KSDAE/TN BERBAK', ]);
    }
}
